### ISSUE TITLE
CSS Help - Brain Hurts

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#61]
Hi Team,

Can someone please help me figure out how to make these float correctly? Alternatively, could you point me to a few properties I could research?

The desktop screen appears correctly. But the second I start shrinking down the screen, I want all three of these text areas to be the width of the screen. I've been at this for a few hours. My CSS powers are very low.

<img width="881" alt="Screen Shot 2020-04-14 at 7 16 52 PM" src="https://user-images.githubusercontent.com/46040704/79291976-e28e9780-7e84-11ea-9c49-b9def78567a3.png">

<img width="842" alt="Screen Shot 2020-04-14 at 7 17 14 PM" src="https://user-images.githubusercontent.com/46040704/79291990-e7534b80-7e84-11ea-97c8-8a0da4a36a20.png">

My current CSS for these (The welcome is the top one in the photo):

```css
#welcome {
    background-color: $dm-gold;
    border-radius: $radius;
    padding: 10px;
    color: white;
    margin-bottom: 10px;
}

#popular {
    background-color: $dm-gold;
    border-radius: $radius;
    padding: 10px;
    color: white;
    margin-bottom: 10px;
    margin-right: 10px;
    min-width: 395px;
    height: 285px;
    float: left;
}

#advert {
    background-color: $dm-gold;
    border-radius: $radius;
    padding: 10px;
    color: white;
    margin-bottom: 10px;
    max-width: 395px;
    height: 285px;
    float: right;
}
```
